# Generated by Django 5.1 on 2024-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=256, unique=True)),
                ("username", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
