# Generated by Django 5.1 on 2024-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todo_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="hashtag",
            field=models.ManyToManyField(
                blank=True, related_name="todos", to="todo.hashtag"
            ),
        ),
    ]
